### ISSUE TITLE
[ZINC Task] Epoch, accuracy, num_correct are all zero and I get a TypeError during the process.

### ISSUE THREAD

**Issue by seanswyi** [facebookresearch/hgnn#5]
Hello. First off, thanks for your hard work and making the repository public. I'm currently a graduate student doing research on deep learning for molecular structures and happened to come across your paper and decided to give it a run. Unfortunately, I'm experiencing some problems and was hoping you could offer some insight.

I downloaded the ZINC dataset as stated in the README file using `python ./get_data.py` from the `data/zinc/` file. Afterwards, I ran the command `python -m torch.distributed.launch --nproc_per_node=1 main.py --task zinc` and observed the program seemed to run fin.

However, the output is like the following:

```Python
INFO - 01/05/20 22:59:12 - 0:00:21 - train data size: 204315
INFO - 01/05/20 22:59:12 - 0:00:21 - dev data size: 24887
INFO - 01/05/20 22:59:12 - 0:00:21 - test data size: 19661
INFO - 01/05/20 22:59:15 - 0:00:23 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.208694, num_correct 0, total 1
INFO - 01/05/20 22:59:31 - 0:00:40 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.118587, num_correct 0, total 401
INFO - 01/05/20 22:59:48 - 0:00:56 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.113731, num_correct 0, total 801
INFO - 01/05/20 23:00:04 - 0:01:13 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.110204, num_correct 0, total 1201
INFO - 01/05/20 23:00:20 - 0:01:29 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.109226, num_correct 0, total 1601
INFO - 01/05/20 23:00:37 - 0:01:46 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.108269, num_correct 0, total 2001
INFO - 01/05/20 23:00:54 - 0:02:02 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.107856, num_correct 0, total 2401
INFO - 01/05/20 23:01:10 - 0:02:19 - rank 0, train phase of epoch 0: accuracy 0.000000, loss 0.107517, num_correct 0, total 2801
```
And it continue like this. Perhaps my understanding of the paper is insufficient, but as you can see only the loss seems to be decreasing and other than that there's not really any way for us to see what's happening. Is this normal behavior?

Also, after a couple of hours I get the error message:

```Python
Traceback (most recent call last):
  File "main.py", line 134, in <module>
    gnn_task.run_gnn()
  File "/home/user1/hgnn/task/GraphPredictionTask.py", line 99, in run_gnn
    dev_acc, dev_loss = self.evaluate(epoch, dev_loader, 'dev', model, loss_function)
  File "/home/user1/hgnn/task/GraphPredictionTask.py", line 122, in evaluate
    accuracy, loss = self.report_epoch_stats()
  File "/home/user1/hgnn/task/BaseTask.py", line 53, in report_epoch_stats
    group = dist.new_group(range(self.args.world_size))
TypeError: 'NoneType' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/user1conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user1/anaconda3/envs/user1conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user1/anaconda3/envs/user1conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/user1/anaconda3/envs/user1conda/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user1/anaconda3/envs/user1conda/bin/python', '-u', 'main.py', '--local_rank=0', '--task', 'zinc']' returned non-zero exit status 1.
```

As you can see, there seems to be two errors that are causing the program to crash. Honestly speaking, I haven't done any debugging or checking yet, but I opened this Issue because I believed that the program should run without any problem if I did so in the same setting you guys did.

It would be great if you guys could shed some light on what's happening and whatever I'm doing incorrectly. Thanks again!

**Comment by seanswyi** [comment]
1. Realized that someone had already opened a similar Issue, which answered my question.
2. I hadn't given the `world_size` argument as I thought that had a default value.
